from time import sleep
import config
import keyboard
import openai
from f import get_prompt, type_text


def get_code_from_openai(
    prompt_: str,
    model: str = "code-davinci-002",
    temperature: float = 0.5,
    max_tokens: int = 100,
    top_p: float = 1,
    frequency_penalty: float = 0,
    presence_penalty: float = 0,
):
    """
    Get code from OpenAI.

    Args:
        prompt_: The prompt to give to OpenAI.
        model: The model to use.
        temperature: The temperature to use.
        max_tokens: The maximum number of tokens to use.
        top_p: The top_p to use.
        frequency_penalty: The frequency_penalty to use.
        presence_penalty: The presence_penalty to use.

    Returns:
        The code generated by OpenAI.
    """
    number_of_characters = len(prompt_)
    max_number_of_characters = 20000
    if number_of_characters > max_number_of_characters:
        print("The prompt is too long. Please shorten it.")
        prompt_ = prompt_[-max_number_of_characters:]
    number_of_characters = len(prompt_)
    max_tokens = 7000 - number_of_characters // 4
    openai.api_key = config.OPENAI_API_KEY
    response = openai.Completion.create(
        model=model,
        prompt=prompt_,
        temperature=temperature,
        max_tokens=max_tokens,
        top_p=top_p,
        frequency_penalty=frequency_penalty,
        presence_penalty=presence_penalty,
        stop=["\n\n\n", "###", "\r\n\r\n\r\n"],
    )
    # pretty_print the response
    import pprint

    pprint.pprint(response)
    text = response.choices[0].text
    print(f"text: {text}")
    with open("openai_response.txt", "a", encoding="utf-8") as file:
        file.write(text)
    return text


def main(
    model: str,
    temperature: float,
    max_tokens: int,
    top_p: float,
    frequency_penalty: float,
    presence_penalty: float,
):
    prompt = get_prompt()
    text = get_code_from_openai(
        prompt,
        model,
        temperature,
        max_tokens,
        top_p,
        frequency_penalty,
        presence_penalty,
    )
    type_text(text)


def speak(text: str) -> None:
    """
    This function takes a string as an argument and speaks it.

    Args:
        text (str): The text to be spoken.

    Returns:
        None
    """
    import win32com.client as wincl

    speak = wincl.Dispatch("SAPI.SpVoice")
    speak.Speak(text)


if __name__ == "__main__":
    max_tokens = None
    temperature = 1
    top_p = 1
    frequency_penalty = 0.3
    presence_penalty = 0.1
    import sys

    if len(sys.argv) > 1:
        max_tokens = int(sys.argv[1])
    elif len(sys.argv) > 2:
        max_tokens = int(sys.argv[1])
        temperature = float(sys.argv[2])
    elif len(sys.argv) > 3:
        max_tokens = int(sys.argv[1])
        temperature = float(sys.argv[2])
        top_p = float(sys.argv[3])
    elif len(sys.argv) > 4:
        max_tokens = int(sys.argv[1])
        temperature = float(sys.argv[2])
        top_p = float(sys.argv[3])
        frequency_penalty = float(sys.argv[4])
    elif len(sys.argv) > 5:
        max_tokens = int(sys.argv[1])
        temperature = float(sys.argv[2])
        top_p = float(sys.argv[3])
        frequency_penalty = float(sys.argv[4])
        presence_penalty = float(sys.argv[5])
    while True:
        key = "ctrl+q"
        if keyboard.is_pressed(key):
            print(f"{key} pressed")
            main(
                model="code-davinci-002",
                temperature=temperature,
                max_tokens=max_tokens,
                top_p=top_p,
                frequency_penalty=frequency_penalty,
                presence_penalty=presence_penalty,
            )
            speak("Done")
        else:
            sleep(0.1)
# improve the time complexity of above python code
